### ISSUE TITLE
Going uphill while wearing sometimes bugs out

### ISSUE THREAD

**Issue by dongle-r** [mallrat208/Rail-Roads#1]
When attempting to move uphill while wearing a pair the rail riders, there sometimes is an issue with the player not actually going uphill and simply reversing direction after climbing a couple of blocks. I am not entirely sure it is a specific issue with your mod, or rather an issue with minecarts as a whole.

**Comment by mallrat208** [comment]
If possible, could you get a screenshot example of a ramp/hill it fails on?

The actual entity for the Rail Riders is a based off of EntityMinecartEmpty, the default minecart you ride. so it shouldn't  run into issues but it's very much possible I maybe didn't make it update position properly

**Comment by dongle-r** [comment]
Actually I think it may be a problem with my own mod for rails. Your mod works perfectly find after testing it a bunch of times.
